--- 

title: "Assigment - Naive Bayes DIY" 

author: 

  - name author here - Samuel 

  - name reviewer here - Robert 

date: "`r format(Sys.time(), '%d %B, %Y')`" 

output: 

   html_notebook: 

    toc: true 

    toc_depth: 2 

--- 

 

 

```{r} 

library(tidyverse) 

library(tm) 

library(caret) 

library(wordcloud) 

library(e1071) 

``` 

 

 

#Business understanding 

To identify fake news and real news 

#data understanding 

 

```{r} 

url <- "" 

rawdata <- read.csv(url) 

``` 

 

 

```{r} 

#It takes too long to process, so I will reduce the sample size. My computer struggles to handle the dataset 

rawdata <- rawdata[-c(2:16000),] 

``` 

 

#data preparation 

 

```{r} 

rawdata <- rawdata[-1] 

rawdata <- rawdata[-1] 

rawdata <- rawdata[-1] 

``` 

 

```{r} 

rawdata <- mutate(rawdata,label = recode(label,"1" = "")) 

``` 

 

 

```{r} 

rawdata$label <- rawdata$label %>%  factor %>% relevel("Fake") 

class(rawdata$label) 

``` 

 

#word map 

```{r} 

Fake <- rawdata %>% filter(label == "Fake") 

Real <- rawdata %>% filter(label == "Real") 

``` 

 

```{r} 



wordcloud(Real$text,max.words = 25, scale = c(4,0.8),colors = c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue")) 

``` 

 

 

 

```{r} 

rawCorpus <- Corpus(VectorSource(rawdata$text)) 

inspect(rawCorpus[1:3]) 

``` 

 

 

```{r} 

cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers) 

``` 

 

```{r} 

cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords,stopwords()) %>% tm_map(removePunctuation) 

``` 

 

 

```{r} 

cleanCorpus <- cleanCorpus %>% tm_map(stripWhitespace) 

``` 

 

#Compare  

```{r} 

tibble(Raw = rawCorpus$content[1:3],Clean = cleanCorpus$content[1:3]) 

``` 

 

 

```{r} 

cleanDTM <- cleanCorpus %>% DocumentTermMatrix() 

inspect(cleanDTM) 

``` 

 

 

#Training and testing data 

```{r} 

set.seed(1234) 

trainIndex <- createDataPartition(rawdata$label,p = .75,list = FALSE,times = 1) 

``` 

 

 

```{r} 

trainDataFrame <- rawdata[trainIndex,] 

``` 

 

 

```{r} 

testDataFrame <- rawdata[-trainIndex,] 

trainCorpus <- cleanCorpus[trainIndex] 

testCorpus <- cleanCorpus[-trainIndex] 

trainDTM <- cleanDTM[trainIndex,] 

testDTM <- cleanDTM[-trainIndex,] 

``` 

 

 

```{r} 

freqWords <- trainDTM %>% findFreqTerms(5) 

trainDTM <- DocumentTermMatrix(trainCorpus,list(dictionary = freqWords)) 

testDTM <- DocumentTermMatrix(testCorpus,list(dictionary = freqWords)) 

``` 

 

 

```{r} 

convert_counts <- function(x){ 

  x <- ifelse(x > 0,1,0) %>% factor(levels = c(0,1),labels = c("No","Yes"))} 

nColsDTM <- dim(trainDTM)[2] 

trainDTM <- apply(trainDTM,MARGIN = 2,convert_counts) 

testDTM <- apply(testDTM,MARGIN = 2,convert_counts) 

head(trainDTM[,1:10]) 

``` 

 

#Modeling and Evaluation 

```{r} 

nbayesModel <- naiveBayes(trainDTM,trainDataFrame$label,laplace = 1) 

``` 

 

 

```{r} 

predVec <- predict(nbayesModel,testDTM) 

confusionMatrix(predVec,testDataFrame$label,positive = "Fake",dnn = c("Prediction","True")) 

``` 